# Generated by Django 5.0.4 on 2024-04-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
    ]
